# Por padrão utilizar a lingua inglêsa.
swagger: '2.0'

info:
  description: Api de lista de apolices a serem integradas com parceiro # 
  version: 1.0.0
  title: Policy Assistances Integration Manager
  contact:
    name: Jean Paul Ramos
    url: http://hdixbbs1:7990/projects/HSE/repos/ins-ply-party-assistance-origindata-manager/browse # ins-ply-assistance-origin-data-list-be
    email: jean.ramos@hdi.com.br

host: 'api.ins-ply-party-assistance-origindata-manager.ins-sales-clusters-dev.cloud.goog'
# host: 'api.ins-ply-assistance-origin-data-list-be.endpoints.ins-sales-clusters-dev.cloud.goog'
basePath: /Insurance/policy/data/v1
# sugesão usar /insurance/policy/data/v1

tags:
  - name: Policy
    description: Policy Assistances Integration
schemes:
  - https

securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
  oauth2_key:
    authorizationUrl: 'https://openapi-dev.hdi.com.br/corporate/security/v1/authorize'
    flow: implicit
    type: oauth2
    x-google-issuer: hdi-corporate-auth@ins-cross-security-auth-dev.iam.gserviceaccount.com
    x-google-jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/hdi-corporate-auth@ins-cross-security-auth-dev.iam.gserviceaccount.com
    x-google-audiences: api.hdi.com.br

security:
  - api_key: []
  - oauth2_key: []
  # oauth2_key: [] Não utilizar -

parameters:
  companyId:
    in: header
    name: X-Company-Id
    required: true
    type: string
    description: Id of the Company that is using the API.
  applicationId:
    in: header
    name: X-Application-Id
    required: true
    type: string
    description: Id of the Application that is using the API.
  userId:
    in: header
    name: X-User-Id
    required: true
    type: string
    description: Id of the User that is using the API.
  traceId:
    in: header
    name: X-Trace-Id
    required: true
    type: string
    description: Id of trace to track the API.    
  policyCode:
    in: query
    name: policyCode
    required: false
    type: string
    description: Code of the insurance policy
  startCreationDate:
    name: startCreationDate
    in: query
    type: string
    format: date
    description: Start Creation Date
    required: false
  endCreationDate:
    name: endCreationDate
    in: query
    type: string
    format: date
    description: End Creation Date
    required: false
  integrationStatus:
    in: query
    name: integrationStatus
    required: true
    type: integer
    format: int32
    description: the Integration Status to target request, such as 1-pending, 2-processing, 3-done
  skip:
    in: query
    name: skip
    type: integer
    format: int32
    required: true
    description: Records Skip
  limit:
    in: query
    name: limit
    type: integer
    format: int32
    required: true
    description: Records limit
  policyAssistance:
    in: body
    name: request
    description: Policy Entity # melhorar a descrição.
    required: true
    schema: 
        $ref: '#/definitions/Policy'  


responses: # Consultar https://hdi-docs-enterprise.readme.io/hdi-docs/docs/contratos-de-api-swaggers#estrutura-b%C3%A1sica.
# Ajustar o response conforme a documentação
  200-Ok:
    description: Successful
    schema:
      $ref: '#/definitions/PolicyList'
  204-Ok:
    description: Successful
  400-BadRequest:
    description: Bad request
    schema:
      $ref: '#/definitions/ErrorResponse' #
  401-Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/ErrorResponse' #
  403-Forbidden:
    description: Forbidden
    schema:
      $ref: '#/definitions/ErrorResponse' #
  404-DataNotFound:
    description: Data not found
    schema:
      $ref: '#/definitions/ErrorResponse' #
  405-DataInvalid:
    description: Data input not supplied or invalid
    schema:
      $ref: '#/definitions/ErrorResponse' #
  453-ApiException:
    description: App business error
    schema:
      $ref: '#/definitions/BusinessError' #
  500-Exception:
    description: Exception
    schema:
      $ref: '#/definitions/ErrorResponse' #

paths:
  /policies/assistances:
    get:
      tags:
        - Policy
      summary: Policy Assistances List
      description: Policy Assistance List
      operationId: getPolicyAssistanceList
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/companyId'
        - $ref: '#/parameters/applicationId'
        - $ref: '#/parameters/userId'
        - $ref: '#/parameters/traceId'
        - $ref: '#/parameters/policyCode'
        - $ref: '#/parameters/startCreationDate'
        - $ref: '#/parameters/endCreationDate'
        - $ref: '#/parameters/integrationStatus'
        - $ref: '#/parameters/skip'
        - $ref: '#/parameters/limit'

      responses:
        '200':
          $ref: '#/responses/200-Ok'
        '400':
          $ref: '#/responses/400-BadRequest'
        '401':
          $ref: '#/responses/401-Unauthorized'
        '403':
          $ref: '#/responses/403-Forbidden'
        '404':
          $ref: '#/responses/404-DataNotFound'
        '405':
          $ref: '#/responses/405-DataInvalid'
        '500':
          $ref: '#/responses/500-Exception'
        '453':
          $ref: '#/responses/453-ApiException'

  /policies/assistance:
    put:
      tags:
        - Policy
      summary: Policy Assistance
      description: Policy Assistance
      operationId: setPolicyAssistance
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/companyId'
        - $ref: '#/parameters/applicationId'
        - $ref: '#/parameters/userId'
        - $ref: '#/parameters/traceId'
        - $ref: '#/parameters/policyAssistance'
      responses:
        '204':
          $ref: '#/responses/204-Ok'
        '400':
          $ref: '#/responses/400-BadRequest'
        '401':
          $ref: '#/responses/401-Unauthorized'
        '403':
          $ref: '#/responses/403-Forbidden'
        '404':
          $ref: '#/responses/404-DataNotFound'
        '405':
          $ref: '#/responses/405-DataInvalid'
        '500':
          $ref: '#/responses/500-Exception'
        '453':
          $ref: '#/responses/453-ApiException'

definitions:
  Error:
    type: object
    description: Error Enitity
    properties:
      code:
        type: string
        description: Error ID
      message:
        type: string
        description: Error Description
      nativeMessage:
        type: string
        description: Native Error description
      trackid:
        type: string
        description: (Optional) Track ID of transaction
  ErrorResponse:
    type: object
    description: Error API responses
    properties:
      code:
        type: integer
        format: int32
        description: Error ID
      message:
        type: string
        description: Error Description
      description:
        type: string
        description: Error Details
      errors:
        type: array
        description: Membership Erros
        items:
          $ref: '#/definitions/Error'
  BusinessError:
    type: object
    description: Error API response
    properties:
      code:
        type: integer
        format: int32
        description: Error ID
      message:
        type: string
        description: Error Details
      description:
        type: string
        description: Error Details
      errors:
        type: array
        description: Membership Erros
        items:
          $ref: '#/definitions/ApiError'
      businessNotifications:
        type: array
        description: Membership Erros
        items:
          $ref: '#/definitions/BusinessNotifications'
    title: BusinessError
  ApiError:
    type: object
    properties:
      code:
        type: string
        description: Internal error ID
      description:
        type: string
        description: Detailed error description
      errors:
        type: array
        description: List of errors
        items:
          $ref: '#/definitions/ObjectError'
      message:
        type: string
        description: Basic message error
    title: ApiError
    description: Error API response
  ObjectError:
    type: object
    properties:
      code:
        type: string
        description: Id of the technical exception
      message:
        type: string
        description: Technical message
      nativeMessage:
        type: string
        description: Native error message
      trackId:
        type: string
        description: Track id of transaction process
    title: ObjectError
    description: Error Entity
  BusinessNotifications:
    type: object
    description: Error Entity
    properties:
      code:
        type: string
        description: Error ID
        example: "002"
      description:
        type: string
        description: Error Description
        example: "Oferta de One Click Mockada (Dados Nao Reais)"
      type:
        type: string
        description: info | warning
        example: "info"
      origin:
        type: string
        description: Notification Origin
        example: "offer"
    title: BusinessNotifications
  PolicyList:
    type: object
    description: Policy List Entity
    properties:
      polices:
        type: array
        items:
          $ref: '#/definitions/Policy'
  DomainData:
    type: object
    description: Assistance Status
    properties:
      id:
        type: number
        format: int64
        description: Id of Status        
  Policy:
    type: object
    description: Policy Entity
    properties:
      id:
        type: integer
        format: int64
        description: Policy Id
        example: 1112
      code:
        type: string
        description: Policy Code
        example: "00.000.000.A.000000.000000"
      integrationStatus:
        $ref: '#/definitions/DomainData'
